### ISSUE TITLE
load more

### ISSUE THREAD

**Issue by syrakozz** [inspace-io/INSPullToRefresh#1]
can you plz add load more for both table and collerciton view

**Comment by m1entus** [comment]
Can you explain what do you need ?

**Comment by syrakozz** [comment]
same pull to refresh concept, but from the footer not the header,
so when the user scroll down he can pull from down also to load more

**Comment by m1entus** [comment]
Maybe in future we will, you can do it easy if you need by modyfiing pull to refersh backogrund view.
