### ISSUE TITLE
Extra vertical padding when programmatically calling: ins_beginPullToRefresh()

### ISSUE THREAD

**Issue by mjgaylord** [inspace-io/INSPullToRefresh#3]
I've tried to debug this and figure out why it is happening, but when I display my view controller, the pull-to-refresh component is displayed with extra padding above it. I am using the method `ins_beginPullToRefresh()` to programmatically display the refresh view.

I've attached a screenshot of the issue:

![screen shot 2015-02-25 at 5 35 14 pm](https://cloud.githubusercontent.com/assets/157073/6373645/b0a8fbac-bd14-11e4-8f95-e40a03a83dfb.png)

**Comment by m1entus** [comment]
did you try to set preserveContentInset, maybe you have some exra inset set by automaticallyAdjustsScrollViewInsets ?

**Comment by mjgaylord** [comment]
I've tried setting preserveContentInset to both true and false, but neither works. If it helps here is the initialisation code being called in `viewDidLoad:`

```swift
       tableView.ins_addPullToRefreshWithHeight(60) { scrollView in
            self.datasource.refresh()
        }
        tableView.ins_pullToRefreshBackgroundView.preserveContentInset = true
        tableView.ins_pullToRefreshBackgroundView.dragToTriggerOffset = 60
        let rect = CGRect(x: 0, y: 0, width: CGRectGetWidth(view.frame), height: 60)
        let pullToRefresh = PullToRefresh(frame: rect, noneStateText: "Pull to Refresh", triggeredStateText: "Release to Refresh", loadingStateText: "Loading...")
        tableView.ins_pullToRefreshBackgroundView.delegate = pullToRefresh
        tableView.ins_pullToRefreshBackgroundView.addSubview(pullToRefresh)```

I've checked my scroll view insets, and they are all zero at runtime.

**Comment by m1entus** [comment]
try to set self.collectionView.contentInset = UIEdgeInsetsMake(0.0f, 0.0f, 0.0f, 0.0f);

**Comment by m1entus** [comment]
If you could prepare example for me i am sure that i could help you

**Comment by mjgaylord** [comment]
setting `contentInset` to zero doesn't seem to make a difference. I will put together an example for you. Perhaps that will help me figure out what the problem is.

**Comment by ccxdd** [comment]
I have encountered this bug, when first loaded.
![Uploading QQ20150228-2@2x.png . . .]()

**Comment by ccxdd** [comment]
I have encountered this bug, when first loaded.
![qq20150228-2 2x](https://cloud.githubusercontent.com/assets/6487492/6424401/800c5478-bf33-11e4-9f7e-0facd5dd3b18.png)

**Comment by m1entus** [comment]
I cant reproduce it and need exaple guys :)

**Comment by luosheng** [comment]
I have just encountered the same issue on a production app but sorry I'm not able to create a simpler demo to reproduce it.

I think it might be related to the issue described here: http://stackoverflow.com/questions/19311045/uiscrollview-animation-of-height-and-contentoffset-jumps-content-from-bottom

I've change the following code in `- [INSPullToRefreshBackgroundView beginRefreshing]`
```objective-c
[self.scrollView setContentOffset:CGPointMake(_scrollView.contentOffset.x, -CGRectGetHeight(self.frame) -_externalContentInset.top ) animated:YES];
```
into
```objective-c
[UIView animateWithDuration:0.0 animations:^{
            
} completion:^(BOOL finished) {
    CGPoint p = CGPointMake(self.scrollView.contentOffset.x, -CGRectGetHeight(self.frame) -_externalContentInset.top);
    [self.scrollView setContentOffset:p animated:YES];
}];
```
and it seems to be working for me.
