### ISSUE TITLE
Your demo, did not take the - (void) dealloc, leading to memory problems

### ISSUE THREAD

**Issue by xiongcaixing1986** [inspace-io/INSPullToRefresh#34]
- (void)dealloc {
    [self.tableView ins_removeInfinityScroll];
    [self.tableView ins_removePullToRefresh];
}

**Comment by m1entus** [comment]
It is taking dealloc ..

**Comment by xiongcaixing1986** [comment]
I hit a breakpoint, it is not taking dealloc ..

**Comment by xiongcaixing1986** [comment]
class INSPullToRefreshViewController and INSPullToRefreshCollectionViewController， it is not taking dealloc ..

**Comment by m1entus** [comment]
Okay, thanks thats true, i fixed it.

**Comment by xiongcaixing1986** [comment]
Do not thank
