### ISSUE TITLE
Epmpty table view pull to refresh

### ISSUE THREAD

**Issue by eoboite** [inspace-io/INSPullToRefresh#36]
How do I enable the pull to refresh of table view is empty?

**Comment by m1entus** [comment]
Same as not empty, [self.tableView ins_beginPullToRefresh];

**Comment by eoboite** [comment]
Okay, that worked but for uicollectionview it doesn't work for an empty view. I tested it out on the example app and same issue reproduce. Set the row count from 15 to 0 for collectionview example and the pull to refresh does not work when empty. Am I do something wrong?

**Comment by m1entus** [comment]
Because UICollectionView inherits from UIScrollView, it's as simple as setting self.collectionView.alwaysBounceVertical = YES to get persistent bouncing, no matter how many cells your collection view has.
