### ISSUE TITLE
Wrong center after orientation change

### ISSUE THREAD

**Issue by ogezue** [inspace-io/INSPullToRefresh#39]
After the orientation changes the position of the RefreshControl is wrong because it doesn't adopt the new center automatically.

I fixed it for myself by adding

-(void) updateRefreshView{
    [self layoutSubviews];
}

to the INSPullToRefreshBackgroundViewDelegate.

**Comment by m1entus** [comment]
It isn't a bug, you have to add constraints to superview to make center or make configuration in layoutSubview of your view.
