### ISSUE TITLE
Can use FBKVOController instead of using KVO directly?

### ISSUE THREAD

**Issue by feefly1987** [inspace-io/INSPullToRefresh#41]
if use FBKVOController, we should not write 'ins_removeInfinityScroll' or 'ins_removePullToRefresh' in 'dealloc' method

**Comment by m1entus** [comment]
If you don't like this way, subclass from UIScrollView and inside -(void)dealloc method insert ins_removePullToRefresh , you will not have to make it on each view controller. I don't want to make dependency of FBKVO.

**Comment by m1entus** [comment]
Fixed in different way.
