### ISSUE TITLE
The praise from coramo

### ISSUE THREAD

**Issue by coramo** [inspace-io/INSPullToRefresh#42]
Hi !

This is a very good project.

But I found some faults in use, for example,
- It will be hidden view after in the disable `infinite scroll`.
- need to delete the `refresh view` in the `dealloc`.

So ,I made some modification to your project, if you can accept these changes, please reply me, I will submit the pull request.

https://github.com/coramo/INSPullToRefresh/tree/acfun

**Comment by m1entus** [comment]
I don't see good reason why infinite scroll should be hidden after disable it, and don't know what do you mean in second point.

**Comment by coramo** [comment]
1. If I want to disable the infinite loading,I only delete it from scrollView,but I think `disable` only need to ban the event callback,such as I need to achieve this effect:  

- I need to display the words "no more" to prompt the user when no data to be load


2.Currently , I must write `ins_removeInfinityScroll, ins_removePullToRefresh` in `dealloc` in anywhere is use `INSPullToRefresh` , But i found good idea to fix it . please see https://github.com/coramo/INSPullToRefresh/commit/e7f9c74639ccf8e055b511ab2306375986ed56c1

And, I'm sorry about the semantics .
I english is bad : )

**Comment by m1entus** [comment]
Thanks, i fixed this issues, i have added flag shouldShowWhenDisabled to make first point available
