### ISSUE TITLE
Pushing a View Controller Messes Up the contentOffset

### ISSUE THREAD

**Issue by DaveBatton** [inspace-io/INSPullToRefresh#45]
If the user initiates an update and then pushes into a new view controller, then endRefresh is called, then the user pops back to the table view, the content offset is permanently messed up.

It looks like dropping back to the table view adds to the top value of externalContentInset when doing this navigation, leaving the table view in a bad state.

**Comment by DaveBatton** [comment]
In action:

https://www.dropbox.com/s/69tu9ao2e50n602/INSPullToRefreshBug.mp4?dl=0

**Comment by m1entus** [comment]
This issue is because of navigation bar transparency, if you turn it off probably will work fine. I will try figure out what is happening

**Comment by marcape** [comment]
I tried setting the `self.edgesForExtendedLayout = UIRectEdgeNone;` to workaround this issue although I want it to work having extended edges.

**Comment by m1entus** [comment]
The problem is self.automaticallyAdjustsScrollViewInsets set to YES by default. I made workaround for it, pull to refresh will automatically turn off it and set correct contentInset based on navigationBar.

**Comment by marcape** [comment]
pulled the latest update, the issue is still present. :(

**Comment by m1entus** [comment]
set self.automaticallyAdjustsScrollViewInsets = NO in your view controller and manually set contentOffset in viewDidLoad
