### ISSUE TITLE
podspec is not updated to use tag 1.0.8

### ISSUE THREAD

**Issue by rolandkakonyi** [inspace-io/INSPullToRefresh#48]
please fix the following to lines in the podspec file:

`s.version  = '1.0.7'`
`s.source   = { :git => 'https://github.com/inspace-io/INSPullToRefresh.git', :tag => '1.0.7'`

please replace 1.0.7 to 1.0.8.

Note: you can refer to the `s.version` like `:tag => "v#{s.version}"` for less possible errors, then you have to only change the line of `s.version`.

**Comment by m1entus** [comment]
Fixed
