### ISSUE TITLE
Bad behaviour when leaving and returning to view controller while loading

### ISSUE THREAD

**Issue by thomzon** [inspace-io/INSPullToRefresh#51]
If I leave my table view while loading is in progress (e.g. by pushing), and come back to it, the INSPullToRefreshBackgroundView appears in a wrong state, like it has added additional inset to the top of the scrollview.

I could not find a good solution for now in the INSPullToRefreshBackgroundView class, but the issue is linked to KVO happening while the view is offscreen.

For now, I change the enable property of the INSPullToRefreshBackgroundView instance in my viewWillDisappear and viewWillAppear, but it is kind of strange to see the loading indicator disappear/reappear.

![ios simulator screen shot 14 jul 2015 10 17 19](https://cloud.githubusercontent.com/assets/697167/8669086/ba6e20a8-2a11-11e5-9736-1ceabf80ee31.png)
![ios simulator screen shot 14 jul 2015 10 17 27](https://cloud.githubusercontent.com/assets/697167/8669087/ba8e37f8-2a11-11e5-9645-a8516ed431b2.png)

**Comment by m1entus** [comment]
Check https://github.com/inspace-io/INSPullToRefresh/issues/45
