### ISSUE TITLE
Cannot use infinite scrolling with horizontally scrolling uicollectionview

### ISSUE THREAD

**Issue by codeafterhours** [inspace-io/INSPullToRefresh#58]
Any pointers on how to achieve infinite scrolling with a horizontally scrolling single row collection view?

**Comment by m1entus** [comment]
Right now it is not supported

**Comment by codeafterhours** [comment]
Is there any help you could lend as it is quite critical that I have it working for horizontal scrolling too ? Any hints too will be very helpful. FYI, I just need to use it with the default activity indicator.

**Comment by m1entus** [comment]
Look on current implementation and remake it for horizontal, should be easy...
