### ISSUE TITLE
why   refresh control not show when pull down in swift2.0

### ISSUE THREAD

**Issue by hengchengfei** [inspace-io/INSPullToRefresh#59]
![2015-10-18 12 02 43](https://cloud.githubusercontent.com/assets/3182964/10562467/323d71d2-7590-11e5-8f61-eedeaaf77145.png)
![2015-10-18 12 03 46](https://cloud.githubusercontent.com/assets/3182964/10562468/3eeec9e4-7590-11e5-831c-c8c5d85cc58e.png)

**Comment by m1entus** [comment]
I am sure you didn't copy assets for Lappsy, and you should probably top view.backgroundColor = UIColor.redColor(), v view is not added anywhere ?

**Comment by hengchengfei** [comment]
thank you.

HUD.xcassets has copy to the project.

if add the test uiview(v) to backgroundView,it shows ok.

but if add the topview ,it doesn't show.

**Comment by hengchengfei** [comment]
I forget the follow code:

<code>self.tableView.ins_pullToRefreshBackgroundView.delegate = pullToRefresh </code>
