### ISSUE TITLE
refresh location not at center

### ISSUE THREAD

**Issue by hengchengfei** [inspace-io/INSPullToRefresh#60]
XCode7.1 Swift2.1

<code>self.tableView.ins_beginPullToRefresh()</code>

![1](https://cloud.githubusercontent.com/assets/3182964/11012540/0112e0f6-8530-11e5-81d2-0d27c8cc1e12.png)

**Comment by m1entus** [comment]
You need to add constaints to the backound of pull to refresh vie to be on center as in example, o setup frame in layoutSubviews. This not depends on swift and ios version.
