### ISSUE TITLE
Crash at deinit

### ISSUE THREAD

**Issue by andrew8712** [inspace-io/INSPullToRefresh#61]
Crashlytics says that my app sometimes crashes at deinit method, implemented as per docs say:

    deinit {
        tableView.ins_removeInfinityScroll()
        tableView.ins_removePullToRefresh()
    }

Crash log:
    Thread : Crashed: com.apple.main-thread
    0  MobileCatalog                  488220 @objc NewsfeedViewController.__deallocating_deinit (NewsfeedViewController.swift)
    1  MobileCatalog                  487964 @objc NewsfeedViewController.__deallocating_deinit (NewsfeedViewController.swift:26)
    2  CoreFoundation                 649858185 -[__NSArrayM dealloc] + 148
    3  libobjc.A.dylib                946704231 objc_object::sidetable_release(bool) + 150
    4  UIKit                          720509339 -[UIViewController dealloc] + 1758
    5  UIKit                          720564553 -[UINavigationController dealloc] + 472
    6  CoreFoundation                 649858185 -[__NSArrayM dealloc] + 148
    7  libobjc.A.dylib                946704231 objc_object::sidetable_release(bool) + 150
    8  UIKit                          720509339 -[UIViewController dealloc] + 1758
    9  UIKit                          722581793 -[UITabBarController dealloc] + 640
    10 UIKit                          722327497 -[UIPresentationController .cxx_destruct] + 304
    11 libobjc.A.dylib                946593621 object_cxxDestructFromClass(objc_object*, objc_class*) + 116
    12 libobjc.A.dylib                946634311 objc_destructInstance + 34
    13 libobjc.A.dylib                946634347 object_dispose + 14
    14 UIKit                          722311753 -[UIPresentationController dealloc] + 60
    15 UIKit                          727683289 -[_UIFullscreenPresentationController dealloc] + 60
    16 libobjc.A.dylib                946704231 objc_object::sidetable_release(bool) + 150
    17 UIKit                          720678031 -[UIViewController _didFinishDismissTransition] + 538
    18 UIKit                          722297235 -[UIPresentationController transitionDidFinish:] + 466
    19 UIKit                          722310961 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke_2 + 192
    20 UIKit                          720106807 -[_UIViewControllerTransitionContext completeTransition:] + 90
    21 UIKit                          719120821 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 540
    22 UIKit                          719119509 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 204
    23 UIKit                          719119247 -[UIViewAnimationState animationDidStop:finished:] + 78
    24 QuartzCore                     711342673 CA::Layer::run_animation_callbacks(void*) + 252
    25 libdispatch.dylib              954088407 _dispatch_client_callout + 22
    26 libdispatch.dylib              954146673 _dispatch_main_queue_callback_4CF$VARIANT$mp + 1524
    27 CoreFoundation                 650541421 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 8
    28 CoreFoundation                 650534503 __CFRunLoopRun + 1574
    29 CoreFoundation                 649826585 CFRunLoopRunSpecific + 520
    30 CoreFoundation                 649826053 CFRunLoopRunInMode + 108
    31 GraphicsServices               802437833 GSEventRunModal + 160
    32 UIKit                          719306517 UIApplicationMain + 144
    33 MobileCatalog                  561304 main (AppDelegate.swift:16)
    34 libdyld.dylib                  954390643 start + 2

Did I miss anything?

**Comment by m1entus** [comment]
In newesr version pull to refresh is automaticly deallocated, no need to do this

**Comment by andrew8712** [comment]
Good to know, thanks! I'd be good idea to remove this from README though ;)
