### ISSUE TITLE
Can you explain adjustedHeightFromScrollViewContentSize?

### ISSUE THREAD

**Issue by cerupcat** [inspace-io/INSPullToRefresh#62]
I'm currently having an issue where calling ```[self.tableView ins_beginInfinityScroll];``` to trigger the initial loading is causing the infinite scroll indicator to start lower than it should be.

I've tracked this down to ```adjustedHeightFromScrollViewContentSize```. If I comment out the following everything works correctly:

```    if(self.scrollView.contentSize.height < remainingHeight) {
        return remainingHeight;
    }```

What does this check provide? I noticed the issue I'm seeing is that the contentHeight is 0 (empty tableView state). When moving from an empty tableView to a non-empty, the loading using ```ins_beginInfinityScroll``` puts the loader in the wrong initial place. I know removing the code fixes everything, but I'm not sure what the side effects will be.

**Comment by cerupcat** [comment]
@m1entus Why is this closed? There's an issue with the position of the UIActivityIndicatorView being in the wrong place initially. I'd like to contribute a fix, but it's hard without the question above being answered.

**Comment by m1entus** [comment]
adjustedHeightFromScrollViewContentSize should guarantee that indicator will be always on the bottom
