### ISSUE TITLE
Orientation change problem (insets are off)

### ISSUE THREAD

**Issue by lm2s** [inspace-io/INSPullToRefresh#68]
I found that when the orientation changes, the tableView/scrollView contentInset is not properly reset, resulting in the pull to refresh view being half shown and the scrollbar inset being off.

Screenshot while idle after orientation change (Portrait -> Landscape):
![Screenshot while idle after orientation change (Portrait -> Landscape)](https://cld.pt/dl/download/51eb25ce-2620-4a76-80a5-2637e422440c/INSPullToRefresh%20idle%20after%20orientation%20change.png)

Screenshot showing the scrollbar wrong inset:
![Screenshot of the scrollbar with wrong inset](https://cld.pt/dl/download/97ecce2e-c2fa-4772-a6e9-9dfbbfe90826/Screen%20Shot%202015-12-01%20at%2012.53.20.png)

I did the following to fix it on my view controller:
```
override func didRotateFromInterfaceOrientation(fromInterfaceOrientation: UIInterfaceOrientation) {
    let statusBarHeight = UIApplication.sharedApplication().statusBarFrame.height
    
    var delta : CGFloat = 0.0
    if let navigationController = self.navigationController {
        if navigationController.navigationBarHidden == false {
            let navigationBarHeight = navigationController.navigationBar.frame.size.height
            delta += navigationBarHeight
        }
    }
    
    if UIApplication.sharedApplication().statusBarHidden == false {
        delta += statusBarHeight
    }
    
    tableView.frame = self.view.bounds
    tableView.contentInset.top = delta
    tableView.scrollIndicatorInsets.top = delta
}
```

This should be automatically done by INSPullToRefresh, or am I wrong?

**Comment by m1entus** [comment]
Should be fixed in version 1.1.0, if you still will have this bug, please reopen this issue.
