### ISSUE TITLE
The circle animation is not invisible

### ISSUE THREAD

**Issue by zymxxx** [inspace-io/INSPullToRefresh#69]
A' viewcontroller has a circle refresh , if you push to B and back to A, the A'cicle is not invisible.

My English is poor,so i want to you can get my mean!

**Comment by zymxxx** [comment]
I find this. http://stackoverflow.com/questions/12413459/why-cant-i-set-the-opacity-of-a-layer-after-a-cabasicanimation-finished
`animationGroup.removedOnCompletion = NO;`maybe is userful.

**Comment by zymxxx** [comment]
hey man ,the circle load also have this problem.you also should fix it.

**Comment by m1entus** [comment]
Done thanks
