### ISSUE TITLE
Method swizzling crash

### ISSUE THREAD

**Issue by kunalsood** [inspace-io/INSPullToRefresh#71]
Seeing a crash here, on device, iPhone 6 Plus running iOS 9.1

![screen shot 2015-12-08 at 11 57 09 am](https://cloud.githubusercontent.com/assets/1951423/11649282/6637b0f2-9da3-11e5-9a3e-356fa3b4546a.png)

**Comment by m1entus** [comment]
I removed swizzling and should be fixed now.
