### ISSUE TITLE
UICollectionView

### ISSUE THREAD

**Issue by math609** [inspace-io/INSPullToRefresh#72]
Awfull gap at the top of the CollectionView It does work correctly on the tableview.
![screen shot 2015-12-08 at 6 25 23 pm](https://cloud.githubusercontent.com/assets/173856/11671854/2ad35b52-9dd9-11e5-88e9-524dca5044c6.png)

**Comment by m1entus** [comment]
Hope that will not have this issue anymore. Thanks
