### ISSUE TITLE
iPad layout issue

### ISSUE THREAD

**Issue by gurhub** [inspace-io/INSPullToRefresh#78]
When I use library with iPad device and type of INSLabelPullToRefresh, layout not fits in landscape mode. 

![screen shot 2016-02-26 at 15 52 20](https://cloud.githubusercontent.com/assets/3050929/13354052/12d72220-dca1-11e5-917d-0efddeadad32.png)

**Comment by m1entus** [comment]
It is working fine, check example. You are doing it wrong.
