### ISSUE TITLE
Pulll to refresh not working if collectionView cells not filling whole screen

### ISSUE THREAD

**Issue by asaturg** [inspace-io/INSPullToRefresh#85]
Hello 

Pulll to refresh not working if collectionView cells not filling whole screen.  In case of tableView everything is working!

![Image](http://realizeit.co/tests/pullNotWorking.png)

**Comment by m1entus** [comment]
UICollectionview - alwaysBounceVertical

**Comment by asaturg** [comment]
@m1entus thank you !
